services:
  fu-search:
    image: ${DOCKERHUB_USERNAME}/fu-search-service:${TAG:-latest}
    container_name: fu-search-service
    ports: [ "8081:8080" ]
    env_file: [ ".env" ]
    restart: unless-stopped
    read_only: true
    tmpfs: [ "/tmp" ]
    security_opt: [ no-new-privileges:true ]
    user: "10001:10001"
    mem_limit: 512m
    cpus: "0.50"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks: [ app-net ]

  fu-sync:
    image: ${DOCKERHUB_USERNAME}/fu-university-service:${TAG:-latest}
    container_name: fu-university-service
    ports: [ "8082:8080" ]
    env_file: [ ".env" ]
    restart: unless-stopped
    read_only: true
    tmpfs: [ "/tmp" ]
    security_opt: [ "no-new-privileges:true" ]
    user: "10001:10001"
    mem_limit: 512m
    cpus: "0.50"
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    networks: [ app-net ]

networks:
  app-net:
    driver: bridge
