name: CI - fu-university-service

on:
  push:
    branches: [master]
    paths:
      - "fu-university-service/**"
      - ".github/workflows/ci-fu-university-service.yml"
  pull_request:
    branches: [master]
    paths:
      - "fu-university-service/**"
      - ".github/workflows/ci-fu-university-service.yml"

jobs:
  build:
    name: Build & publish fu-university-service
    uses: ./.github/workflows/_java-docker-build.yml
    secrets: inherit
    with:
      service_dir: fu-university-service
      image_name_suffix: fu-university-service
      java_version: "21"
